{"version":1,"ops":[{"type":1,"author":{"id":"e3aba1afe19faebf95f2ee776f4836c7caaabd1c"},"timestamp":1408738040,"metadata":{"github-id":"MDU6SXNzdWU0MDk0NTUzMA==","github-url":"https://github.com/perl11/potion/issues/73","origin":"github"},"title":"When building under vagrant/precise32, build succeeds but some tests, examples fail","message":"Here's the make test output:\nvagrant@precise32:~/noitop/potion$ make test\ntest/runtests.sh -q\nrunning potion API tests\n.............\nOK (13 tests)\n\nrunning GC tests\n......\nOK (6 tests)\n\nrunning bin/potion VM tests\n....................\n*\\* test/flow/except.pn: expected \u003cTRY 1\nTRY ERROR!\nRESUMING\nSUCCESS\nTRY 2\nSUCCESS\nnil\u003e, but got \u003cTRY 1\nnilTRY 2\nSUCCESS\nnil\u003e\n..................................................................\nrunning bin/potion compiler tests\n....................\n*\\* test/flow/except.pn: expected \u003cTRY 1\nTRY ERROR!\nRESUMING\nSUCCESS\nTRY 2\nSUCCESS\nnil\u003e, but got \u003cTRY 1\nnilTRY 2\nSUCCESS\nnil\u003e\n..................................................................\nrunning bin/potion JIT tests\n....................Segmentation fault\n\n*\\* test/flow/except.pn: expected \u003cTRY 1\nTRY ERROR!\nRESUMING\nSUCCESS\nTRY 2\nSUCCESS\nnil\u003e, but got \u003c\u003e\n..................................................................\n3 FAILS (258 tests)\nvagrant@precise32:~/noitop/potion$","files":null}]}